<?php

/**
 * @file
 * Contains orbit_webform.module.
 */

declare(strict_types=1);

use Drupal\webform\WebformInterface;

/**
 * Implements hook_ENTITY_TYPE_create().
 *
 * https://www.drupal.org/project/webform/issues/3118427#comment-13494283 - Add
 * a default purge time.
 */
function orbit_webform_webform_create(WebformInterface $webform) {

  // Set purge authenticated and anonymous users submissions.
  $webform->setSetting('purge', 'all');
  // Set purge submissions more than 30 days old.
  $webform->setSetting('purge_days', 30);
}
